id: P000618
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:52:14.472796
source_metadata:
  id: bdr:W29032
  title: སྒྲ་དང་སྡེབ་སྦྱོར།
  author: ''
  volumes:
    49e4806653c24e5aab233a27fe6953a5:
      image_group_id: I5740
      title: ''
      volume_number: 1
      total_pages: 775
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
