id: P000618
initial_creation_type: ocr
source_metadata:
  id: bdr:W29032
  title: སྒྲ་དང་སྡེབ་སྦྱོར།
  author: ''
  volumes:
    49e4806653c24e5aab233a27fe6953a5:
      image_group_id: I5740
      title: ''
      volume_number: 1
      total_pages: 775
